'use strict';
const LIGHT_KEY='lightPhenomenonProgressV1';
const LIGHT_FILES=['propagation.html','reflection.html','plane-mirror.html','refraction.html','dispersion.html','invisible-light.html'];
let memoryProgress={},storageOK=true;
function getProgress(){try{const p=JSON.parse(localStorage.getItem(LIGHT_KEY)||'{}');return p&&typeof p==='object'&&!Array.isArray(p)?p:{}}catch{storageOK=false;return memoryProgress}}
function putProgress(p){memoryProgress=p;try{localStorage.setItem(LIGHT_KEY,JSON.stringify(p))}catch{storageOK=false}showStorage();}
function showStorage(){const n=document.getElementById('storage-note');if(n&&!storageOK)n.textContent='浏览器限制了本地存储，本次页面仍可正常学习和答题，但跨页进度可能无法保存。'}
const page=location.pathname.split('/').pop()||'index.html';
document.querySelectorAll('.main-nav a').forEach(a=>{if(a.getAttribute('href')===page)a.setAttribute('aria-current','page')});
function renderProgress(){const p=getProgress();let done=0;LIGHT_FILES.forEach((file,i)=>{const card=document.querySelector('[data-course="'+i+'"]');if(p[file]?.done)done++;if(card){const label=card.querySelector('.status');label.textContent=p[file]?.done?'✓ 已完成':p[file]?.visited?'学习中':'未学习';label.classList.toggle('done',!!p[file]?.done)}});const t=document.getElementById('home-progress-text'),b=document.getElementById('home-progress');if(t)t.textContent='已完成 '+done+' / 6 章';if(b)b.style.width=done/6*100+'%';showStorage();}
if(LIGHT_FILES.includes(page)){const p=getProgress();p[page]={...(p[page]||{}),visited:true};putProgress(p);}
renderProgress();
const complete=document.getElementById('complete-chapter');
if(complete){if(getProgress()[page]?.done)complete.textContent='✓ 本章已完成';complete.addEventListener('click',()=>{const p=getProgress();p[page]={...(p[page]||{}),done:true};putProgress(p);complete.textContent='✓ 本章已完成';});}
document.getElementById('reset-progress')?.addEventListener('click',()=>{if(confirm('清空光现象专题的学习进度？不会影响其他专题。')){putProgress({});renderProgress();}});
document.getElementById('restart-exam')?.addEventListener('click',()=>{if(confirm('清空本次作答并重新开始检测？'))location.reload();});
const quiz=document.getElementById('quiz');
if(quiz){const all=quiz.dataset.chapter==='all',list=LIGHT_QUESTIONS.filter(q=>all||q.chapter===Number(quiz.dataset.chapter)),first=new Map(),letters=['A','B','C','D'];function score(){const n=[...first.values()].filter(Boolean).length;document.getElementById('quiz-summary').textContent='已提交 '+first.size+' / '+list.length+' 题；首次答对 '+n+' 题。'+(first.size===list.length?' 已完成，重做不改变首次成绩。':'');}
list.forEach((q,index)=>{const card=document.createElement('section');card.className=all?'question card':'question';card.innerHTML='<form><fieldset><legend>'+(index+1)+'. '+q.q+'</legend>'+q.o.map((o,j)=>'<label class="option"><input type="checkbox" name="choice" value="'+j+'"><span><b>'+letters[j]+'.</b> '+o[0]+'</span></label>').join('')+'</fieldset><div class="actions"><button class="primary" type="submit">提交答案</button><button type="button" class="retry" hidden>重做本题</button></div><div class="feedback" aria-live="polite" aria-atomic="true"></div></form>';quiz.appendChild(card);
const form=card.querySelector('form'),feedback=card.querySelector('.feedback'),retry=card.querySelector('.retry'),submit=card.querySelector('[type=submit]');
form.addEventListener('submit',e=>{e.preventDefault();if(submit.disabled)return;const selected=[...form.querySelectorAll('input:checked')].map(x=>Number(x.value));if(!selected.length){feedback.innerHTML='<div class="verdict wrong">请先选择至少一个选项。</div>';return;}const right=q.o.map((o,j)=>o[1]?j:-1).filter(j=>j>=0),ok=right.length===selected.length&&right.every(j=>selected.includes(j)),missing=right.filter(j=>!selected.includes(j)),extra=selected.filter(j=>!right.includes(j));if(!first.has(index))first.set(index,ok);
feedback.innerHTML='<div class="verdict '+(ok?'':'wrong')+'"><b>'+(ok?'✓ 回答正确':'✗ 回答不完全正确')+'</b> · 正确答案：'+right.map(j=>letters[j]).join('、')+(missing.length?'<br>漏选：'+missing.map(j=>letters[j]).join('、'):'')+(extra.length?'<br>错选：'+extra.map(j=>letters[j]).join('、'):'')+'</div>'+q.o.map((o,j)=>'<div class="analysis"><b class="'+(o[1]?'yes':'no')+'">'+letters[j]+' · '+(o[1]?'正确选项':'错误选项')+' · '+(selected.includes(j)?'你已选':'你未选')+'</b><p>'+o[2]+'</p></div>').join('');
form.querySelectorAll('input').forEach(x=>x.disabled=true);submit.disabled=true;retry.hidden=false;score();});
retry.addEventListener('click',()=>{form.reset();form.querySelectorAll('input').forEach(x=>x.disabled=false);submit.disabled=false;retry.hidden=true;feedback.innerHTML='';form.querySelector('input').focus();});});}
const svg=document.getElementById('lab-svg'),result=document.getElementById('lab-result');
const line=(x1,y1,x2,y2,color='#163832',dash=false,arrow=false)=>'<line x1="'+x1+'" y1="'+y1+'" x2="'+x2+'" y2="'+y2+'" stroke="'+color+'" stroke-width="3" '+(dash?'stroke-dasharray="7 5" ':'')+(arrow?'marker-end="url(#'+(color==='#c95443'?'red':'blue')+')"':'')+'/>';
const text=(x,y,t)=>'<text x="'+x+'" y="'+y+'">'+t+'</text>';
const defs='<defs><marker id="red" markerWidth="9" markerHeight="9" refX="8" refY="3" orient="auto" markerUnits="strokeWidth"><path d="M0 0 L8 3 L0 6Z" fill="#c95443"/></marker><marker id="blue" markerWidth="9" markerHeight="9" refX="8" refY="3" orient="auto" markerUnits="strokeWidth"><path d="M0 0 L8 3 L0 6Z" fill="#246fa7"/></marker></defs>';
function angleArc(a,side){if(!a)return '';const r=a*Math.PI/180,sign=side==='left'?-1:1,x=320+sign*45*Math.sin(r),y=255-45*Math.cos(r);return '<path d="M320 210 A45 45 0 0 '+(sign<0?0:1)+' '+x+' '+y+'" fill="none" stroke="#768c86" stroke-width="2"/>'+text(320+sign*72*Math.sin(r/2)-4,255-72*Math.cos(r/2),sign<0?'i':'r');}
function draw(body){if(svg)svg.innerHTML=defs+body;}
function bind(ids,fn){ids.forEach(id=>document.getElementById(id)?.addEventListener('input',fn));fn();}
const lab=document.querySelector('[data-lab]')?.dataset.lab;
if(lab==='pinhole'){bind(['screen-distance'],()=>{const d=Number(document.getElementById('screen-distance').value),x=320+d,h=60*d/200;document.getElementById('screen-value').textContent=d;
draw(line(50,170,605,170,'#85998f',true)+line(120,230,120,110,'#c95443',false,true)+line(320,40,320,166)+line(320,174,320,300)+line(x,45,x,295,'#768c86')+line(120,110,320,170,'#c95443',false,true)+line(320,170,x,170+h,'#c95443',false,true)+line(120,230,320,170,'#246fa7',false,true)+line(320,170,x,170-h,'#246fa7',false,true)+line(x,170-h,x,170+h,'#c95443',false,true)+text(85,275,'物体')+text(290,325,'小孔')+text(x-25,325,'光屏')+text(35,30,'物体上端 → 像的下端'));
result.textContent='孔屏距离 '+d+'；像高 / 物高 = '+(d/200).toFixed(2)+'。实际光线落在屏上，形成倒立实像。';});}
if(lab==='reflection'){bind(['incident-angle'],()=>{const a=Number(document.getElementById('incident-angle').value),r=a*Math.PI/180,dx=185*Math.sin(r),dy=185*Math.cos(r);document.getElementById('incident-value').textContent=a+'°';
draw('<rect x="40" y="255" width="560" height="24" fill="#c9bceb"/>'+line(40,255,600,255)+line(320,35,320,310,'#85998f',true)+line(320-dx,255-dy,320,255,'#c95443',false,true)+line(320,255,320+dx,255-dy,'#246fa7',false,true)+angleArc(a,'left')+angleArc(a,'right')+text(329,40,'法线')+text(80,315,'平面镜')+text(60,45,'入射角 i = '+a+'°')+text(430,45,'反射角 r = '+a+'°'));
result.textContent=a===0?'垂直入射：入射角、反射角都为 0°，光沿原路返回。两条光线在图上重合。':'入射角 '+a+'°，反射角 '+a+'°。光线与镜面的夹角为 '+(90-a)+'°，不要把它当作入射角。';});}
if(lab==='mirror'){bind(['mirror-distance'],()=>{const d=Number(document.getElementById('mirror-distance').value),x=320-d,im=320+d;document.getElementById('mirror-value').textContent=d;
draw('<rect x="320" y="30" width="10" height="245" fill="#c9bceb"/>'+line(320,30,320,275)+line(x,245,x,105,'#c95443',false,true)+line(im,245,im,105,'#246fa7',true,true)+[145,190].map(y=>line(x,105,320,y,'#c95443',false,true)+line(320,y,x,2*y-105,'#246fa7',false,true)+line(320,y,im,105,'#85998f',true)).join('')+line(x,290,320,290,'#85998f',true)+line(320,290,im,290,'#85998f',true)+text(x-20,320,'物距 '+d)+text(im-45,320,'像距 '+d)+text(x-15,85,'物体')+text(im-15,85,'虚像')+text(295,22,'镜面'));
result.textContent='物距 = 像距 = '+d+'，物像距离 = '+(d*2)+'。物像等大；镜后灰色虚线只是反向延长线。';});}
if(lab==='refraction'){bind(['media','refract-angle'],()=>{const a=Number(document.getElementById('refract-angle').value),inWater=document.getElementById('media').value==='water-air',n1=inWater?1.33:1,n2=inWater?1:1.33,i=a*Math.PI/180,r=Math.asin(n1/n2*Math.sin(i)),rd=r*180/Math.PI;document.getElementById('refract-value').textContent=a+'°';
draw('<rect x="20" y="20" width="600" height="150" fill="'+(inWater?'#d3eaf3':'#f9f5e9')+'"/><rect x="20" y="170" width="600" height="150" fill="'+(inWater?'#f9f5e9':'#d3eaf3')+'"/>'+line(20,170,620,170)+line(320,25,320,315,'#85998f',true)+line(320-140*Math.sin(i),170-140*Math.cos(i),320,170,'#c95443',false,true)+line(320,170,320+140*Math.sin(r),170+140*Math.cos(r),'#246fa7',false,true)+text(35,50,inWater?'水':'空气')+text(35,215,inWater?'空气':'水')+text(425,55,'入射角 '+a+'°')+text(430,285,'折射角 '+rd.toFixed(1)+'°'));
result.textContent=a===0?'垂直入射：方向不变，但在两种介质中的传播速度不同。':(inWater?'水 → 空气：远离法线，折射角大于入射角。':'空气 → 水：靠近法线，折射角小于入射角。')+' 折射角约 '+rd.toFixed(1)+'°。';});}
if(lab==='color'){const update=()=>{const bits=[...document.querySelectorAll('.rgb')].map(x=>x.checked?1:0),material=document.getElementById('material').value,masks={all:[1,1,1],red:[1,0,0],green:[0,1,0],blue:[0,0,1]},out=bits.map((v,i)=>v*masks[material][i]),rgb=a=>'rgb('+a.map(x=>x*255).join(',')+')',names={'000':'无光 / 暗','100':'红','010':'绿','001':'蓝','110':'黄','101':'品红','011':'青','111':'白'},mode=document.getElementById('color-mode').value;
draw('<rect x="60" y="65" width="180" height="170" rx="12" fill="'+rgb(bits)+'" stroke="#163832"/><rect x="400" y="65" width="180" height="170" rx="12" fill="'+rgb(out)+'" stroke="#163832"/>'+text(65,45,'入射：'+names[bits.join('')])+text(400,45,(mode==='surface'?'反射':'透射')+'：'+names[out.join('')])+line(260,150,375,150,'#246fa7',false,true)+text(260,190,'材料筛选')+text(55,285,'理想 RGB 通道模型；黑色块表示几乎没有光到达眼睛。'));
result.textContent='入射光：'+names[bits.join('')]+'；'+(mode==='surface'?'反射光':'透射光')+'：'+names[out.join('')]+'。材料不会凭空创造入射光中没有的色光（本模型不含荧光）。';};['material','color-mode'].forEach(id=>document.getElementById(id).addEventListener('input',update));document.querySelectorAll('.rgb').forEach(x=>x.addEventListener('change',update));update();}
if(lab==='spectrum'){const data={ir:'红外线：比可见红光波长更长。常用于传统遥控器、红外探测；人眼看不见，仪器可以转换为可见显示。',visible:'可见光：人眼能直接感知的电磁波范围。图上彩带和色块是示意，不代表准确的光谱尺度。',uv:'紫外线：比可见紫光波长更短。某些材料受激发产生可见荧光；荧光不是人眼直接看到了紫外线。'};
function update(band){document.querySelectorAll('[data-band]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.band===band)));draw('<rect x="35" y="95" width="170" height="90" rx="8" fill="#ffbd83"/><rect x="225" y="95" width="190" height="90" rx="8" fill="#a9dece"/><rect x="435" y="95" width="170" height="90" rx="8" fill="#c9bceb"/>'+text(85,145,'红外线')+text(285,145,'可见光')+text(485,145,'紫外线')+line(590,245,50,245,'#246fa7',false,true)+text(255,280,'波长逐渐变长 ←')+text(35,40,'波段排列示意，不按比例')+'<rect x="'+({ir:35,visible:225,uv:435}[band])+'" y="90" width="'+(band==='visible'?190:170)+'" height="100" rx="8" fill="none" stroke="#163832" stroke-width="4"/>');result.textContent=data[band];}
document.querySelectorAll('[data-band]').forEach(b=>b.addEventListener('click',()=>update(b.dataset.band)));update('ir');}
